blog/rfw/urls.py
from rest_framework import routers
from blog.views import UserViewSet, CategoryViewSet, ArticleViewSet


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'category', CategoryViewSet)
router.register(r'article', ArticleViewSet)

blog/urls.py
from django.urls import path
from blog.views import HomeView, ArticleView, PostArticleView, DeleteArticleView, SearchArticleView

app_name = 'blog'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article'),
    path('post/', PostArticleView.as_view(), name='post'),
    path('delete/<int:pk>', DeleteArticleView.as_view(), name='delete'),
    path('search/', SearchArticleView.as_view(), name='search'),
    # path('search/<str>', SearchResultView.as_view(), name='search_result'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.rfw.urls import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('blog.urls')),
]

blog/models/article.py
from django.db import models
from blog.models.attribute import User, Category


class Article(models.Model):
    title = models.CharField(max_length=100)
    detail = models.TextField(max_length=5000)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    # @property
    # def age(self):
    #     return Unko.objects.get(id=1)

    def __str__(self):
        return self.title


# class Unko(models.Model):
#     text = models.TextField(max_length=100)

#     def __str__(self):
#         return self.text

blog/models/attribute.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Category(models.Model):
    category_name = models.CharField(max_length=20)

    def __str__(self):
        return self.category_name

blog/forms.py
from django import forms

from blog.models.article import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'


class SearchForm(forms.Form):
    keyword = forms.CharField(label='キーワード', max_length=100, required=True)

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, FormView
from rest_framework import filters, viewsets

from blog.forms import ArticleForm, SearchForm
from blog.models.article import Article
from blog.models.attribute import Category, User
from blog.rfw.serializers import (ArticleSerializer, CategorySerializer,
                                  UserSerializer)


class HomeView(ListView):
    template_name = 'home.html'
    model = Article


class ArticleView(DetailView):
    template_name = 'article.html'
    model = Article


class PostArticleView(CreateView):
    template_name = 'post.html'
    form_class = ArticleForm
    success_url = reverse_lazy('blog:home')


class DeleteArticleView(DeleteView):
    template_name = 'delete.html'
    model = Article
    success_url = reverse_lazy('blog:home')


class SearchArticleView(FormView):
    template_name = 'search.html'
    form_class = SearchForm
    model = Article
    # success_url = reverse_lazy('blog:search_result')


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class ArticleViewSet(viewsets.ModelViewSet):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer

blog/templates/article.html
{% extends 'base.html' %} {% block content %}
<section>
    <h1>{{ object.title }}</h1>
    <div>{{ object.detail }}</div>
    <div>{{ object.pub_date }}</div>
    <div><a href="{% url 'blog:delete' object.id %}">記事を削除する</a></div>
    <div>{{ object.age }}</div>
</section>
{% endblock %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<meta charset="utf-8">

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>

<body>
    <header>
        <h1>ブログです</h1>
    </header>
    <nav>
        <ul>
            {% block nav %}
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'blog:post' %}">投稿する</a></li>
            <li><a href="{% url 'blog:search' %}">検索する</a></li>
            {% endblock %}
        </ul>
    </nav>
    <article>
        {% block content %}
        {% endblock %}
    </article>
    <aside>
        <section>
            <h1>記事検索</h1>
            <ul>
                {% comment %}
                <form method="POST" action="{% url 'blog:search' %}">
                    {% csrf_token %}
                    <div>
                        <input type="text">
                    </div>
                    <div>
                        <input type="submit" value="検索">
                    </div>
                </form>
                {% endcomment %}
            </ul>
        </section>
        <section>
            <h1>最新記事</h1>
            <ul>
                {% block recent %}
                {% endblock %}
            </ul>
        </section>
        <section>
            <h1>アーカイブ</h1>
            <ul>
                {% block archive %}
                {% endblock %}
            </ul>
        </section>
        <section>
            <h1>カテゴリー</h1>
            <ul>
                {% block category %}
                {% endblock %}
            </ul>
        </section>
    </aside>
    <footer>
    </footer>
</body>

</html>

blog/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<section>
    本当に削除しますか？
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="削除する">
    </form>
</section>
{% endblock %}

blog/templates/home.html
{% extends 'base.html' %}

{% block content %}
{% for article in article_list reversed %}
<section>
    <h2><a href='{% url "blog:article" article.id %}'>{{ article.title }}</a></h2>
    <div>{{ article.detail | safe | linebreaksbr}}</div>
</section>
{% endfor %}
{% endblock %}

blog/templates/post.html
{% extends 'base.html' %}
{% block title %} 記事の投稿 {% endblock %}

{% block content %}
<section>
    <form method="POST" action="{% url 'blog:post' %}">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">submit</button>
    </form>
</section>
{% endblock %}

blog/templates/search.html
{% extends 'base.html' %}
{% block content %}
<section>
    <form method="POST" action="{% url 'blog:search_result' %}">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">search</button>
    </form>
</section>
{% endblock %}